website:
  image: scher200/php-www-webdav
  restart: unless-stopped
  volumes:
    - "./data/www:/htmlfiles"
  expose:
    - "80"
  environment:
    SHARED_DIR: /htmlfiles
    AUTH_USER: admin
    AUTH_PASS: admin

